Todo list using react
sediqullahbadakhsh/react-todo-list pull request #1
Opened 2022-03-22 19:56 UTC by sediqullahbadakhsh

in this milestone, I have created a react app using routers, hooks, and functional componenets.

2022-03-25 16:11 UTC, leopiresgoss requested changes
Good job @sediqullahbadakhsh :1st_place_medal: 

What I liked about your project:
:heavy_check_mark:  Well structured and organized
:heavy_check_mark: No linter issues

However, I have some suggestions for you in order to improve your project:

- Your todo app is not working, I couldn't add a task and it is throwing those errors:
![image](https://user-images.githubusercontent.com/61767582/160158658-3461e65b-c56d-4cd3-a0ba-d1a4d597c359.png)

- Kindly, update your readme file in a professional way.

Happy coding :slightly_smiling_face:

2022-04-26 13:05 UTC, Have-Samuel reviewed
Good job done with the code :+1: , I just left a few comments below, please try to look into them so that the code becomes more clear.

And feel free to reach out to me in case of any issues.

2022-04-26 13:05 UTC, Have-Samuel commented on src/components/InputTodo.js
> +        <input
Nice code :100:

2022-04-26 13:05 UTC, Have-Samuel commented on src/components/TodoContainer.js
> +import Navbar from './Navbar';
Good job done with the modules :+1:

2022-04-26 13:05 UTC, Have-Samuel commented on src/components/TodoItem.js
> +  };
Good job done with the functions :100:

2022-04-26 15:09 UTC, Have-Samuel approved these changes
Good Job done, Clean code :100:

2022-04-26 15:17 UTC, merged